Modification de l'IA difficile
CoursIUTAmiens2023/DUBUT_GROSSET_LEFRANCOIS_PINCHON_PROJET pull request #17
Opened 2024-03-13 21:26 UTC by Enzo-py

2024-03-13 21:49 UTC, ElFloww requested changes

2024-03-13 21:49 UTC, ElFloww commented on src/R5.08.Project.Forms/Models/Bot.cs
> +                        string tmp = tmp_grid.m_Grid.PrintString();
TEMPORARY STRING WTFF REMOVE THIS SHIT OR RENAME IT

2024-03-13 21:49 UTC, ElFloww commented on src/R5.08.Project.Forms/Models/Bot.cs
>                      Puissance4 tmp_grid = (Puissance4)v_Puissance4.Clone();
Not use "tmp", use more meaningful variable name, and with conventional naming "v_Grid" for example

2024-03-13 21:49 UTC, ElFloww commented on src/R5.08.Project.Forms/Models/puissance4.cs
> +        private Random rd = new Random();
v_Random

2024-03-13 21:49 UTC, ElFloww commented on src/R5.08.Project.Forms/Models/puissance4.cs
> +                    if (v_Neighbour.m_Player == -1) { continue; }
Prefer the opposite condition

2024-03-14 19:23 UTC, Enzo-py commented on src/R5.08.Project.Forms/Models/Bot.cs
> +                        string tmp = tmp_grid.m_Grid.PrintString();
De 1. en français mon gars stp.
De 2. Ouai faudrait le retirer
De 3. C'est pas toi qui a passé une aprem à début cet enfer.

2024-03-14 19:30 UTC, Enzo-py commented on src/R5.08.Project.Forms/Models/puissance4.cs
> +                    if (v_Neighbour.m_Player == -1) { continue; }
Trop d'imbrication, c'est plus propre comme ca.

Continue ne pose pas de problème d'optimisation

2024-03-18 10:05 UTC, merged